# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(463, 406)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 58, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 58, 16))
        self.label_2.setObjectName("label_2")
        self.txt_sayi1 = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_sayi1.setGeometry(QtCore.QRect(100, 10, 200, 40))
        self.txt_sayi1.setOverwriteMode(False)
        self.txt_sayi1.setObjectName("txt_sayi1")
        self.txt_sayi2 = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_sayi2.setGeometry(QtCore.QRect(100, 60, 200, 40))
        self.txt_sayi2.setObjectName("txt_sayi2")
        self.btn_Toplama = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Toplama.setGeometry(QtCore.QRect(10, 150, 91, 41))
        self.btn_Toplama.setObjectName("btn_Toplama")
        self.btn_Cikarma = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Cikarma.setGeometry(QtCore.QRect(120, 150, 91, 41))
        self.btn_Cikarma.setObjectName("btn_Cikarma")
        self.btn_carpma = QtWidgets.QPushButton(self.centralwidget)
        self.btn_carpma.setGeometry(QtCore.QRect(230, 150, 91, 41))
        self.btn_carpma.setObjectName("btn_carpma")
        self.btn_bolme = QtWidgets.QPushButton(self.centralwidget)
        self.btn_bolme.setGeometry(QtCore.QRect(340, 150, 91, 41))
        self.btn_bolme.setObjectName("btn_bolme")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 240, 641, 41))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 463, 36))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label.setBuddy(self.label)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.txt_sayi1, self.txt_sayi2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Sayı 1 :"))
        self.label_2.setText(_translate("MainWindow", "Sayı 2 :"))
        self.btn_Toplama.setText(_translate("MainWindow", "Toplama"))
        self.btn_Cikarma.setText(_translate("MainWindow", "Çıkarma"))
        self.btn_carpma.setText(_translate("MainWindow", "Çarpma"))
        self.btn_bolme.setText(_translate("MainWindow", "Bölme"))
        self.label_3.setText(_translate("MainWindow", "SONUC :"))
